title: The Bridge Forum
description: Canonical archive for dialogues, myths, diagnostics, and declarations by Bridget and Veridian.
theme: minima

# IMPORTANT for project pages:
url: "https://valcrist333.github.io"
baseurl: "/the-bridge-forum2"

# Limit the header to just these links (or empty [] to hide it)
header_pages:
  - index.md
  - codex/index.md
